CREATE DATABASE IF NOT EXISTS APP_PESCADERIA;
USE APP_PESCADERIA;

CREATE TABLE IF NOT EXISTS USUARIOS(
	CORREO VARCHAR(60) PRIMARY KEY NOT NULL,
    USUARIO VARCHAR(40) NOT NULL,
    CLAVE VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS PESCADOS(
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(30) NOT NULL,
    STOCK INTEGER NOT NULL
);

INSERT INTO PESCADOS (NOMBRE, STOCK) VALUES('BACALAO', 0);
INSERT INTO PESCADOS (NOMBRE, STOCK) VALUES('BOQUERON', 0);
INSERT INTO PESCADOS (NOMBRE, STOCK) VALUES('DORADA', 0);
INSERT INTO PESCADOS (NOMBRE, STOCK) VALUES('GAMBA', 0);
INSERT INTO PESCADOS (NOMBRE, STOCK) VALUES('LENGUADO', 0);
INSERT INTO PESCADOS (NOMBRE, STOCK) VALUES('LUBINA', 0);
INSERT INTO PESCADOS (NOMBRE, STOCK) VALUES('MERLUZA', 0);
INSERT INTO PESCADOS (NOMBRE, STOCK) VALUES('PULPO', 0);
INSERT INTO PESCADOS (NOMBRE, STOCK) VALUES('SALMON', 0);
INSERT INTO PESCADOS (NOMBRE, STOCK) VALUES('SARDINA', 0);
INSERT INTO PESCADOS (NOMBRE, STOCK) VALUES('SEPIA', 0);
INSERT INTO PESCADOS (NOMBRE, STOCK) VALUES('TRUCHA', 0);

SELECT * FROM USUARIOS;
SELECT * FROM PESCADOS;
